### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/AzureDocumentDbTypeProvider#19]
Hi @stewart-r ,

I just came across this type provider while dealing with https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121.  I'll add a separate issue about that

I had been meaning to look into a TP for DocumentDb for some time.   Would you be interested in collaborating to iterate on this further?

One thing we often to to help enable collaboration is to move projects to http://github.com/fsprojects.  This helps raise the visibility of the project, helps attract contributors and also gives a "backup admin" for basic tasks.  If you'd like to move the project to "fsprojects" that would be great

Let me know what you think

cc @sergey-tihon @isaacabraham

**Comment by stewart-r** [comment]
Hi,

Yes, of course. I would be delighted to do whatever you like in this regard.

In all honesty, I really didnt anywhere near as far as I'd have liked on it.  As you can no doubt see I ran out of steam before it really provided much value.

How do I go about moving it to fsprojects?

**Comment by sergey-tihon** [comment]
Here is the process description https://github.com/fsprojects/FsProjectsAdmin#onboarding-process
I already sent you invitation to organization

**Comment by stewart-r** [comment]
Thanks sergey - I have transfered to fsprojects-transfer organisation

**Comment by sergey-tihon** [comment]
Welcome aboard!

**Comment by stewart-r** [comment]
thanks :-)
